name: Update MLB Matchups Daily

on:
  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mlb-statsapi

      - name: Run Python script
        run: python generate_matchups.py

      - name: Commit output file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add matchup_results.json
          git commit -m "Daily update of matchups"
          git push
