name: Update Matchups Daily

on:
  schedule:
    - cron: '0 14 * * *'  # Every day at 2:00 PM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate matchup data
        run: python scripts/generate_matchups.py

      - name: Commit and push JSON data
        run: |
          git config --global user.name "Grube13"
          git config --global user.email "grubebrandon@yahoo.com"
          git add matchup_results.json
          git commit -m "Update matchup data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
