name: Update Matchups Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate matchup data
        run: python generate_matchups.py

      - name: Configure Git
        run: |
          git config --global user.name "Grube13"
          git config --global user.email "grubebrandon@yahoo.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git add matchup_results.json
          git commit -m "Update matchup data" || echo "No changes to commit"
          git push
